services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DB_HOST
        value: switchyard.proxy.rlwy.net
      - key: DB_DATABASE
        value: railway
      - key: DB_PORT
        value: 30543
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: dUswAfWtBbobuSnQdrdnCFyMxjoUTcAj
